export type IntentType = 'bug_report' | 'feature_request' | 'praise' | 'churn_signal' | 'question'

export type FeedbackSentiment = {
  polarity: number
  intensity: 'mild' | 'moderate' | 'strong' | 'extreme'
  emotions: string[]
}

export type FeedbackUnit = {
  id: string
  text: string
  sourceChannel: string
  accountId: string
  accountName: string
  topicId: string
  topicLabel: string
  intentType: IntentType
  sentiment: FeedbackSentiment
  date: string
  sourceUrl?: string
  isStarred: boolean
  duplicateCount?: number
  confidence: number
}

export const MOCK_FEEDBACK_UNITS: FeedbackUnit[] = [
  // --- Report Export (Acme Corp heavy) ---
  {
    id: 'fu-1',
    text: 'The report export hangs on files over 10k rows and times out after 30s. We\'ve tried 3 times. This is blocking our end-of-month process.',
    sourceChannel: 'Support ticket',
    accountId: 'acct-1',
    accountName: 'Acme Corp',
    topicId: 'tax-report-export',
    topicLabel: 'Report Export',
    intentType: 'bug_report',
    sentiment: { polarity: -0.8, intensity: 'strong', emotions: ['frustrated', 'anxious'] },
    date: '2026-02-22',
    sourceUrl: 'https://support.example.com/tickets/4421',
    isStarred: true,
    duplicateCount: 12,
    confidence: 0.94,
  },
  {
    id: 'fu-2',
    text: 'We need Excel export, PDF doesn\'t work for our workflow. The finance team refuses to use CSV.',
    sourceChannel: 'Survey',
    accountId: 'acct-1',
    accountName: 'Acme Corp',
    topicId: 'tax-report-export',
    topicLabel: 'Report Export',
    intentType: 'feature_request',
    sentiment: { polarity: -0.4, intensity: 'moderate', emotions: ['frustrated'] },
    date: '2026-02-20',
    isStarred: false,
    confidence: 0.91,
  },
  {
    id: 'fu-3',
    text: 'Export finally worked after applying the workaround your team suggested — thanks for the quick help!',
    sourceChannel: 'Intercom',
    accountId: 'acct-1',
    accountName: 'Acme Corp',
    topicId: 'tax-report-export',
    topicLabel: 'Report Export',
    intentType: 'praise',
    sentiment: { polarity: 0.7, intensity: 'moderate', emotions: ['grateful'] },
    date: '2026-02-18',
    isStarred: false,
    confidence: 0.88,
  },
  {
    id: 'fu-4',
    text: 'Report export keeps crashing when using date filters. This has been broken since last Tuesday.',
    sourceChannel: 'Zendesk',
    accountId: 'acct-3',
    accountName: 'Initech LLC',
    topicId: 'tax-report-export',
    topicLabel: 'Report Export',
    intentType: 'bug_report',
    sentiment: { polarity: -0.6, intensity: 'moderate', emotions: ['frustrated'] },
    date: '2026-02-19',
    isStarred: false,
    confidence: 0.92,
  },
  {
    id: 'fu-5',
    text: 'Would love scheduled report exports — set it and forget it, emailed to stakeholders every Monday.',
    sourceChannel: 'G2',
    accountId: 'acct-6',
    accountName: 'Beta Labs',
    topicId: 'tax-report-export',
    topicLabel: 'Report Export',
    intentType: 'feature_request',
    sentiment: { polarity: 0.2, intensity: 'mild', emotions: ['hopeful'] },
    date: '2026-02-17',
    isStarred: false,
    confidence: 0.85,
  },

  // --- Login Failures ---
  {
    id: 'fu-6',
    text: 'SSO login is broken after the Jan 14 deploy. 4 of our users can\'t access the platform at all.',
    sourceChannel: 'Support ticket',
    accountId: 'acct-2',
    accountName: 'Globex Industries',
    topicId: 'tax-login-fail',
    topicLabel: 'Login Failures',
    intentType: 'bug_report',
    sentiment: { polarity: -0.9, intensity: 'extreme', emotions: ['angry', 'frustrated'] },
    date: '2026-02-19',
    sourceUrl: 'https://support.example.com/tickets/4480',
    isStarred: true,
    duplicateCount: 8,
    confidence: 0.97,
  },
  {
    id: 'fu-7',
    text: 'Login page returns a 500 error intermittently. Happens about 1 in 5 attempts.',
    sourceChannel: 'Zendesk',
    accountId: 'acct-5',
    accountName: 'TechStart Inc',
    topicId: 'tax-login-fail',
    topicLabel: 'Login Failures',
    intentType: 'bug_report',
    sentiment: { polarity: -0.5, intensity: 'moderate', emotions: ['frustrated'] },
    date: '2026-02-21',
    isStarred: false,
    confidence: 0.93,
  },
  {
    id: 'fu-8',
    text: 'MFA codes from the authenticator app are being rejected even when entered within the time window.',
    sourceChannel: 'Support ticket',
    accountId: 'acct-1',
    accountName: 'Acme Corp',
    topicId: 'tax-login-fail',
    topicLabel: 'Login Failures',
    intentType: 'bug_report',
    sentiment: { polarity: -0.6, intensity: 'moderate', emotions: ['confused', 'frustrated'] },
    date: '2026-02-23',
    isStarred: false,
    confidence: 0.90,
  },
  {
    id: 'fu-9',
    text: 'We\'re evaluating alternatives because our team literally cannot log in half the time. This is a dealbreaker.',
    sourceChannel: 'Sales call',
    accountId: 'acct-2',
    accountName: 'Globex Industries',
    topicId: 'tax-login-fail',
    topicLabel: 'Login Failures',
    intentType: 'churn_signal',
    sentiment: { polarity: -0.95, intensity: 'extreme', emotions: ['angry', 'disappointed'] },
    date: '2026-02-24',
    isStarred: true,
    confidence: 0.96,
  },

  // --- Dashboard Loading ---
  {
    id: 'fu-10',
    text: 'Dashboard takes 12 seconds to load with our dataset. The old version was instant.',
    sourceChannel: 'Intercom',
    accountId: 'acct-1',
    accountName: 'Acme Corp',
    topicId: 'tax-dashboard-load',
    topicLabel: 'Dashboard Loading',
    intentType: 'bug_report',
    sentiment: { polarity: -0.7, intensity: 'strong', emotions: ['frustrated', 'disappointed'] },
    date: '2026-02-15',
    isStarred: false,
    confidence: 0.91,
  },
  {
    id: 'fu-11',
    text: 'Can you add a loading skeleton or progress bar? The blank screen makes it look like it\'s broken.',
    sourceChannel: 'Survey',
    accountId: 'acct-5',
    accountName: 'TechStart Inc',
    topicId: 'tax-dashboard-load',
    topicLabel: 'Dashboard Loading',
    intentType: 'feature_request',
    sentiment: { polarity: -0.2, intensity: 'mild', emotions: ['confused'] },
    date: '2026-02-16',
    isStarred: false,
    confidence: 0.84,
  },

  // --- Search Speed ---
  {
    id: 'fu-12',
    text: 'Love the new search speed — much faster than before. Great improvement!',
    sourceChannel: 'G2',
    accountId: 'acct-3',
    accountName: 'Initech LLC',
    topicId: 'tax-search-speed',
    topicLabel: 'Search Speed',
    intentType: 'praise',
    sentiment: { polarity: 0.8, intensity: 'strong', emotions: ['delighted', 'grateful'] },
    date: '2026-02-15',
    isStarred: true,
    confidence: 0.95,
  },
  {
    id: 'fu-13',
    text: 'Search is blazing fast now. Whatever you did in the last release, keep it up.',
    sourceChannel: 'Intercom',
    accountId: 'acct-6',
    accountName: 'Beta Labs',
    topicId: 'tax-search-speed',
    topicLabel: 'Search Speed',
    intentType: 'praise',
    sentiment: { polarity: 0.9, intensity: 'strong', emotions: ['delighted'] },
    date: '2026-02-18',
    isStarred: false,
    confidence: 0.92,
  },

  // --- SSO Integration ---
  {
    id: 'fu-14',
    text: 'Please add support for Okta SSO. We can\'t roll out to the rest of the org without it.',
    sourceChannel: 'Sales call',
    accountId: 'acct-1',
    accountName: 'Acme Corp',
    topicId: 'tax-sso',
    topicLabel: 'SSO Integration',
    intentType: 'feature_request',
    sentiment: { polarity: -0.3, intensity: 'moderate', emotions: ['frustrated'] },
    date: '2026-02-20',
    isStarred: false,
    confidence: 0.89,
  },
  {
    id: 'fu-15',
    text: 'SAML integration worked out of the box with our Azure AD — smooth setup.',
    sourceChannel: 'Survey',
    accountId: 'acct-6',
    accountName: 'Beta Labs',
    topicId: 'tax-sso',
    topicLabel: 'SSO Integration',
    intentType: 'praise',
    sentiment: { polarity: 0.6, intensity: 'moderate', emotions: ['satisfied'] },
    date: '2026-02-14',
    isStarred: false,
    confidence: 0.87,
  },

  // --- CSV Import Errors ---
  {
    id: 'fu-16',
    text: 'CSV import fails silently when there are special characters in column headers. No error message at all.',
    sourceChannel: 'Zendesk',
    accountId: 'acct-5',
    accountName: 'TechStart Inc',
    topicId: 'tax-csv-import',
    topicLabel: 'CSV Import Errors',
    intentType: 'bug_report',
    sentiment: { polarity: -0.6, intensity: 'moderate', emotions: ['frustrated', 'confused'] },
    date: '2026-02-12',
    isStarred: false,
    confidence: 0.91,
  },
  {
    id: 'fu-17',
    text: 'Import validation is much better now — it catches duplicate rows and shows clear error messages.',
    sourceChannel: 'Intercom',
    accountId: 'acct-3',
    accountName: 'Initech LLC',
    topicId: 'tax-csv-import',
    topicLabel: 'CSV Import Errors',
    intentType: 'praise',
    sentiment: { polarity: 0.5, intensity: 'moderate', emotions: ['satisfied'] },
    date: '2026-02-10',
    isStarred: false,
    confidence: 0.86,
  },

  // --- Bulk Edit ---
  {
    id: 'fu-18',
    text: 'Bulk edit only lets you change 50 items at a time. We have thousands of records to update — need higher limits.',
    sourceChannel: 'Survey',
    accountId: 'acct-1',
    accountName: 'Acme Corp',
    topicId: 'tax-bulk-edit',
    topicLabel: 'Bulk Edit',
    intentType: 'feature_request',
    sentiment: { polarity: -0.4, intensity: 'moderate', emotions: ['frustrated'] },
    date: '2026-02-08',
    isStarred: false,
    confidence: 0.83,
  },

  // --- Onboarding Flow ---
  {
    id: 'fu-19',
    text: 'The onboarding wizard is so much better than when we first signed up. The checklist format really helps.',
    sourceChannel: 'G2',
    accountId: 'acct-5',
    accountName: 'TechStart Inc',
    topicId: 'tax-onboarding',
    topicLabel: 'Onboarding Flow',
    intentType: 'praise',
    sentiment: { polarity: 0.8, intensity: 'strong', emotions: ['delighted', 'satisfied'] },
    date: '2026-02-20',
    isStarred: false,
    confidence: 0.90,
  },
  {
    id: 'fu-20',
    text: 'The setup process took us 3 weeks. There should be better documentation for enterprise deployments.',
    sourceChannel: 'Survey',
    accountId: 'acct-1',
    accountName: 'Acme Corp',
    topicId: 'tax-onboarding',
    topicLabel: 'Onboarding Flow',
    intentType: 'bug_report',
    sentiment: { polarity: -0.5, intensity: 'moderate', emotions: ['frustrated', 'disappointed'] },
    date: '2026-02-11',
    isStarred: false,
    confidence: 0.82,
  },
  {
    id: 'fu-21',
    text: 'Onboarding video tutorials are excellent — our team was productive on day one.',
    sourceChannel: 'Intercom',
    accountId: 'acct-6',
    accountName: 'Beta Labs',
    topicId: 'tax-onboarding',
    topicLabel: 'Onboarding Flow',
    intentType: 'praise',
    sentiment: { polarity: 0.85, intensity: 'strong', emotions: ['delighted', 'grateful'] },
    date: '2026-02-22',
    isStarred: false,
    confidence: 0.91,
  },

  // --- Pricing Concerns ---
  {
    id: 'fu-22',
    text: 'Your pricing is 3x what we pay for a competitor that does 80% of what you do. We\'re reconsidering.',
    sourceChannel: 'Sales call',
    accountId: 'acct-4',
    accountName: 'Umbrella Co',
    topicId: 'tax-pricing',
    topicLabel: 'Pricing Concerns',
    intentType: 'churn_signal',
    sentiment: { polarity: -0.85, intensity: 'strong', emotions: ['disappointed', 'frustrated'] },
    date: '2026-02-21',
    isStarred: false,
    confidence: 0.94,
  },
  {
    id: 'fu-23',
    text: 'The per-seat pricing doesn\'t make sense for our use case. We have 200 users but only 10 are daily active.',
    sourceChannel: 'Survey',
    accountId: 'acct-4',
    accountName: 'Umbrella Co',
    topicId: 'tax-pricing',
    topicLabel: 'Pricing Concerns',
    intentType: 'feature_request',
    sentiment: { polarity: -0.5, intensity: 'moderate', emotions: ['frustrated'] },
    date: '2026-02-18',
    isStarred: false,
    confidence: 0.88,
  },

  // --- Support Response ---
  {
    id: 'fu-24',
    text: 'Support took 4 days to respond to a P1 ticket. Unacceptable for our tier.',
    sourceChannel: 'Support ticket',
    accountId: 'acct-2',
    accountName: 'Globex Industries',
    topicId: 'tax-support-resp',
    topicLabel: 'Support Response',
    intentType: 'bug_report',
    sentiment: { polarity: -0.9, intensity: 'extreme', emotions: ['angry', 'disappointed'] },
    date: '2026-02-23',
    isStarred: false,
    confidence: 0.96,
  },
  {
    id: 'fu-25',
    text: 'Had a great experience with your support team — Sarah resolved my issue in 20 minutes.',
    sourceChannel: 'Survey',
    accountId: 'acct-3',
    accountName: 'Initech LLC',
    topicId: 'tax-support-resp',
    topicLabel: 'Support Response',
    intentType: 'praise',
    sentiment: { polarity: 0.9, intensity: 'strong', emotions: ['grateful', 'delighted'] },
    date: '2026-02-16',
    isStarred: false,
    confidence: 0.93,
  },
  {
    id: 'fu-26',
    text: 'Your knowledge base articles are outdated. Half the screenshots don\'t match the current UI.',
    sourceChannel: 'Intercom',
    accountId: 'acct-5',
    accountName: 'TechStart Inc',
    topicId: 'tax-support-resp',
    topicLabel: 'Support Response',
    intentType: 'bug_report',
    sentiment: { polarity: -0.4, intensity: 'moderate', emotions: ['frustrated', 'confused'] },
    date: '2026-02-19',
    isStarred: false,
    confidence: 0.85,
  },

  // --- API Documentation ---
  {
    id: 'fu-27',
    text: 'API docs are clear and well-organized. The code samples in Python and JavaScript saved us days.',
    sourceChannel: 'G2',
    accountId: 'acct-3',
    accountName: 'Initech LLC',
    topicId: 'tax-api-docs',
    topicLabel: 'API Documentation',
    intentType: 'praise',
    sentiment: { polarity: 0.85, intensity: 'strong', emotions: ['satisfied', 'grateful'] },
    date: '2026-02-14',
    isStarred: false,
    confidence: 0.92,
  },
  {
    id: 'fu-28',
    text: 'The webhook documentation is missing error response schemas. We\'re guessing at error handling.',
    sourceChannel: 'Support ticket',
    accountId: 'acct-5',
    accountName: 'TechStart Inc',
    topicId: 'tax-api-docs',
    topicLabel: 'API Documentation',
    intentType: 'bug_report',
    sentiment: { polarity: -0.3, intensity: 'mild', emotions: ['confused'] },
    date: '2026-02-17',
    isStarred: false,
    confidence: 0.84,
  },
  {
    id: 'fu-29',
    text: 'Is there a rate limit on the REST API? I couldn\'t find it documented anywhere.',
    sourceChannel: 'Intercom',
    accountId: 'acct-6',
    accountName: 'Beta Labs',
    topicId: 'tax-api-docs',
    topicLabel: 'API Documentation',
    intentType: 'question',
    sentiment: { polarity: -0.1, intensity: 'mild', emotions: ['confused'] },
    date: '2026-02-20',
    isStarred: false,
    confidence: 0.80,
  },

  // --- Mobile Offline ---
  {
    id: 'fu-30',
    text: 'We need offline mode for the mobile app. Our field team works in areas with spotty connectivity.',
    sourceChannel: 'Sales call',
    accountId: 'acct-1',
    accountName: 'Acme Corp',
    topicId: 'tax-mobile-offline',
    topicLabel: 'Mobile Offline',
    intentType: 'feature_request',
    sentiment: { polarity: -0.3, intensity: 'moderate', emotions: ['frustrated'] },
    date: '2026-02-21',
    isStarred: false,
    confidence: 0.87,
  },
  {
    id: 'fu-31',
    text: 'App crashes immediately when losing WiFi connection mid-session. Data is lost every time.',
    sourceChannel: 'Support ticket',
    accountId: 'acct-5',
    accountName: 'TechStart Inc',
    topicId: 'tax-mobile-offline',
    topicLabel: 'Mobile Offline',
    intentType: 'bug_report',
    sentiment: { polarity: -0.7, intensity: 'strong', emotions: ['frustrated', 'angry'] },
    date: '2026-02-22',
    isStarred: false,
    confidence: 0.91,
  },

  // --- Session Timeouts ---
  {
    id: 'fu-32',
    text: 'Session expires after 15 minutes of inactivity. We need at least 1 hour for our workflow.',
    sourceChannel: 'Survey',
    accountId: 'acct-4',
    accountName: 'Umbrella Co',
    topicId: 'tax-session',
    topicLabel: 'Session Timeouts',
    intentType: 'feature_request',
    sentiment: { polarity: -0.4, intensity: 'moderate', emotions: ['frustrated'] },
    date: '2026-02-13',
    isStarred: false,
    confidence: 0.86,
  },

  // --- More Report Export (different accounts) ---
  {
    id: 'fu-33',
    text: 'Export to PDF generates a blank file when the report contains charts. Text-only reports export fine.',
    sourceChannel: 'Zendesk',
    accountId: 'acct-2',
    accountName: 'Globex Industries',
    topicId: 'tax-report-export',
    topicLabel: 'Report Export',
    intentType: 'bug_report',
    sentiment: { polarity: -0.5, intensity: 'moderate', emotions: ['frustrated'] },
    date: '2026-02-24',
    isStarred: false,
    confidence: 0.90,
  },
  {
    id: 'fu-34',
    text: 'The new export queue system is great — I can start an export and come back to it later.',
    sourceChannel: 'Intercom',
    accountId: 'acct-5',
    accountName: 'TechStart Inc',
    topicId: 'tax-report-export',
    topicLabel: 'Report Export',
    intentType: 'praise',
    sentiment: { polarity: 0.6, intensity: 'moderate', emotions: ['satisfied'] },
    date: '2026-02-23',
    isStarred: false,
    confidence: 0.87,
  },

  // --- More Login Failures ---
  {
    id: 'fu-35',
    text: 'Password reset emails are taking over 30 minutes to arrive. Users think the system is broken.',
    sourceChannel: 'Support ticket',
    accountId: 'acct-4',
    accountName: 'Umbrella Co',
    topicId: 'tax-login-fail',
    topicLabel: 'Login Failures',
    intentType: 'bug_report',
    sentiment: { polarity: -0.6, intensity: 'moderate', emotions: ['frustrated', 'confused'] },
    date: '2026-02-20',
    isStarred: false,
    confidence: 0.88,
  },

  // --- Additional units for variety ---
  {
    id: 'fu-36',
    text: 'Can you add dark mode? Staring at a white screen for 8 hours is rough.',
    sourceChannel: 'G2',
    accountId: 'acct-6',
    accountName: 'Beta Labs',
    topicId: 'tax-dashboard-load',
    topicLabel: 'Dashboard Loading',
    intentType: 'feature_request',
    sentiment: { polarity: -0.2, intensity: 'mild', emotions: ['hopeful'] },
    date: '2026-02-19',
    isStarred: false,
    confidence: 0.72,
  },
  {
    id: 'fu-37',
    text: 'If your pricing doesn\'t change by renewal, we\'re moving to Competitor X. Final notice.',
    sourceChannel: 'Sales call',
    accountId: 'acct-4',
    accountName: 'Umbrella Co',
    topicId: 'tax-pricing',
    topicLabel: 'Pricing Concerns',
    intentType: 'churn_signal',
    sentiment: { polarity: -0.95, intensity: 'extreme', emotions: ['angry', 'resigned'] },
    date: '2026-02-25',
    isStarred: true,
    confidence: 0.97,
  },
  {
    id: 'fu-38',
    text: 'Bulk edit is surprisingly intuitive. Our ops team picked it up without any training.',
    sourceChannel: 'Survey',
    accountId: 'acct-3',
    accountName: 'Initech LLC',
    topicId: 'tax-bulk-edit',
    topicLabel: 'Bulk Edit',
    intentType: 'praise',
    sentiment: { polarity: 0.7, intensity: 'moderate', emotions: ['satisfied', 'delighted'] },
    date: '2026-02-12',
    isStarred: false,
    confidence: 0.85,
  },
  {
    id: 'fu-39',
    text: 'How do I set up webhooks for real-time notifications? The docs mention it but don\'t explain the setup.',
    sourceChannel: 'Intercom',
    accountId: 'acct-5',
    accountName: 'TechStart Inc',
    topicId: 'tax-api-docs',
    topicLabel: 'API Documentation',
    intentType: 'question',
    sentiment: { polarity: -0.1, intensity: 'mild', emotions: ['confused'] },
    date: '2026-02-21',
    isStarred: false,
    confidence: 0.78,
  },
  {
    id: 'fu-40',
    text: 'Support response time has been excellent this month — every ticket resolved same day.',
    sourceChannel: 'Survey',
    accountId: 'acct-6',
    accountName: 'Beta Labs',
    topicId: 'tax-support-resp',
    topicLabel: 'Support Response',
    intentType: 'praise',
    sentiment: { polarity: 0.9, intensity: 'strong', emotions: ['grateful', 'satisfied'] },
    date: '2026-02-24',
    isStarred: false,
    confidence: 0.94,
  },
  {
    id: 'fu-41',
    text: 'Our compliance team needs field-level audit logs for every data change. This is a regulatory requirement.',
    sourceChannel: 'Sales call',
    accountId: 'acct-1',
    accountName: 'Acme Corp',
    topicId: 'tax-unclassified',
    topicLabel: 'Unclassified',
    intentType: 'feature_request',
    sentiment: { polarity: -0.3, intensity: 'moderate', emotions: ['anxious'] },
    date: '2026-02-23',
    isStarred: false,
    confidence: 0.61,
  },
  {
    id: 'fu-42',
    text: 'Would be great to have an integration with Tableau for advanced analytics.',
    sourceChannel: 'Survey',
    accountId: 'acct-3',
    accountName: 'Initech LLC',
    topicId: 'tax-unclassified',
    topicLabel: 'Unclassified',
    intentType: 'feature_request',
    sentiment: { polarity: 0.1, intensity: 'mild', emotions: ['hopeful'] },
    date: '2026-02-15',
    isStarred: false,
    confidence: 0.58,
  },
  {
    id: 'fu-43',
    text: 'The notification system keeps sending duplicate alerts. I got 15 emails for the same event.',
    sourceChannel: 'Support ticket',
    accountId: 'acct-2',
    accountName: 'Globex Industries',
    topicId: 'tax-unclassified',
    topicLabel: 'Unclassified',
    intentType: 'bug_report',
    sentiment: { polarity: -0.6, intensity: 'moderate', emotions: ['frustrated', 'annoyed'] },
    date: '2026-02-22',
    isStarred: false,
    confidence: 0.65,
  },
  {
    id: 'fu-44',
    text: 'Dashboard performance is noticeably better after the Feb update. Load time went from 8s to 2s.',
    sourceChannel: 'Intercom',
    accountId: 'acct-5',
    accountName: 'TechStart Inc',
    topicId: 'tax-dashboard-load',
    topicLabel: 'Dashboard Loading',
    intentType: 'praise',
    sentiment: { polarity: 0.75, intensity: 'strong', emotions: ['satisfied', 'surprised'] },
    date: '2026-02-25',
    isStarred: false,
    confidence: 0.89,
  },
  {
    id: 'fu-45',
    text: 'We\'re seriously considering downgrading our plan. The value doesn\'t match what we\'re paying.',
    sourceChannel: 'Sales call',
    accountId: 'acct-2',
    accountName: 'Globex Industries',
    topicId: 'tax-pricing',
    topicLabel: 'Pricing Concerns',
    intentType: 'churn_signal',
    sentiment: { polarity: -0.7, intensity: 'strong', emotions: ['disappointed', 'resigned'] },
    date: '2026-02-25',
    isStarred: false,
    confidence: 0.92,
  },
]
